import { Photo } from "./types";

export const pictures: Photo[] = [
  {
    id: 1,
    projectId: 4,
    fileName: "Kairos (1)",
    fileType: "png",
    imagePath: "/assets/projects/Kairos/Kairos (1).png",
    projectName: "Kairos",
  },
  {
    id: 2,
    projectId: 4,
    fileName: "Kairos (2)",
    fileType: "png",
    imagePath: "/assets/projects/Kairos/Kairos (2).png",
    projectName: "Kairos",
  },
  {
    id: 3,
    projectId: 4,
    fileName: "Kairos (3)",
    fileType: "png",
    imagePath: "/assets/projects/Kairos/Kairos (3).png",
    projectName: "Kairos",
  },
  {
    id: 4,
    projectId: 4,
    fileName: "Kairos (4)",
    fileType: "png",
    imagePath: "/assets/projects/Kairos/Kairos (4).png",
    projectName: "Kairos",
  },
  {
    id: 5,
    projectId: 4,
    fileName: "Kairos (5)",
    fileType: "png",
    imagePath: "/assets/projects/Kairos/Kairos (5).png",
    projectName: "Kairos",
  },
  {
    id: 6,
    projectId: 4,
    fileName: "Kairos (6)",
    fileType: "png",
    imagePath: "/assets/projects/Kairos/Kairos (6).png",
    projectName: "Kairos",
  },
  {
    id: 7,
    projectId: 4,
    fileName: "Kairos (7)",
    fileType: "png",
    imagePath: "/assets/projects/Kairos/Kairos (7).png",
    projectName: "Kairos",
  },
  {
    id: 8,
    projectId: 4,
    fileName: "Kairos (8)",
    fileType: "png",
    imagePath: "/assets/projects/Kairos/Kairos (8).png",
    projectName: "Kairos",
  },
  {
    id: 9,
    projectId: 4,
    fileName: "Kairos (9)",
    fileType: "png",
    imagePath: "/assets/projects/Kairos/Kairos (9).png",
    projectName: "Kairos",
  },
  {
    id: 10,
    projectId: 2,
    fileName: "Portfolio (1)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (1).png",
    projectName: "Portfolio",
  },
  {
    id: 11,
    projectId: 2,
    fileName: "Portfolio (2)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (2).png",
    projectName: "Portfolio",
  },
  {
    id: 12,
    projectId: 2,
    fileName: "Portfolio (3)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (3).png",
    projectName: "Portfolio",
  },
  {
    id: 13,
    projectId: 2,
    fileName: "Portfolio (4)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (4).png",
    projectName: "Portfolio",
  },
  {
    id: 14,
    projectId: 2,
    fileName: "Portfolio (5)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (5).png",
    projectName: "Portfolio",
  },
  {
    id: 15,
    projectId: 2,
    fileName: "Portfolio (6)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (6).png",
    projectName: "Portfolio",
  },
  {
    id: 16,
    projectId: 2,
    fileName: "Portfolio (7)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (7).png",
    projectName: "Portfolio",
  },
  {
    id: 17,
    projectId: 2,
    fileName: "Portfolio (8)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (8).png",
    projectName: "Portfolio",
  },
  {
    id: 18,
    projectId: 2,
    fileName: "Portfolio (9)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (9).png",
    projectName: "Portfolio",
  },
  {
    id: 19,
    projectId: 2,
    fileName: "Portfolio (10)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (10).png",
    projectName: "Portfolio",
  },
  {
    id: 20,
    projectId: 1,
    fileName: "TaskMate (1)",
    fileType: "png",
    imagePath: "/assets/projects/TaskMate/TaskMate (1).png",
    projectName: "TaskMate",
  },
  {
    id: 21,
    projectId: 1,
    fileName: "TaskMate (2)",
    fileType: "png",
    imagePath: "/assets/projects/TaskMate/TaskMate (2).png",
    projectName: "TaskMate",
  },
  {
    id: 22,
    projectId: 1,
    fileName: "TaskMate (3)",
    fileType: "png",
    imagePath: "/assets/projects/TaskMate/TaskMate (3).png",
    projectName: "TaskMate",
  },
  {
    id: 23,
    projectId: 1,
    fileName: "TaskMate (4)",
    fileType: "png",
    imagePath: "/assets/projects/TaskMate/TaskMate (4).png",
    projectName: "TaskMate",
  },
  {
    id: 24,
    projectId: 1,
    fileName: "TaskMate (5)",
    fileType: "png",
    imagePath: "/assets/projects/TaskMate/TaskMate (5).png",
    projectName: "TaskMate",
  },
  {
    id: 25,
    projectId: 1,
    fileName: "TaskMate (6)",
    fileType: "png",
    imagePath: "/assets/projects/TaskMate/TaskMate (6).png",
    projectName: "TaskMate",
  },
  {
    id: 26,
    projectId: 1,
    fileName: "TaskMate (7)",
    fileType: "png",
    imagePath: "/assets/projects/TaskMate/TaskMate (7).png",
    projectName: "TaskMate",
  },
  {
    id: 27,
    projectId: 1,
    fileName: "TaskMate (8)",
    fileType: "png",
    imagePath: "/assets/projects/TaskMate/TaskMate (8).png",
    projectName: "TaskMate",
  },
  {
    id: 28,
    projectId: 3,
    fileName: "MoviePlus (1)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (1).png",
    projectName: "Movie Plus",
  },
  {
    id: 29,
    projectId: 3,
    fileName: "MoviePlus (2)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (2).png",
    projectName: "Movie Plus",
  },
  {
    id: 30,
    projectId: 3,
    fileName: "MoviePlus (3)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (3).png",
    projectName: "Movie Plus",
  },
  {
    id: 31,
    projectId: 3,
    fileName: "MoviePlus (4)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (4).png",
    projectName: "Movie Plus",
  },
  {
    id: 32,
    projectId: 3,
    fileName: "MoviePlus (5)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (5).png",
    projectName: "Movie Plus",
  },
  {
    id: 33,
    projectId: 3,
    fileName: "MoviePlus (6)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (6).png",
    projectName: "Movie Plus",
  },
  {
    id: 34,
    projectId: 3,
    fileName: "MoviePlus (7)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (7).png",
    projectName: "Movie Plus",
  },
  {
    id: 35,
    projectId: 3,
    fileName: "MoviePlus (8)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (8).png",
    projectName: "Movie Plus",
  },
  {
    id: 36,
    projectId: 3,
    fileName: "MoviePlus (9)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (9).png",
    projectName: "Movie Plus",
  },
  {
    id: 37,
    projectId: 3,
    fileName: "MoviePlus (10)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (10).png",
    projectName: "Movie Plus",
  },
  {
    id: 38,
    projectId: 5,
    fileName: "Typy (1)",
    fileType: "png",
    imagePath: "/assets/projects/Typy/Typy (1).png",
    projectName: "Typy",
  },
  {
    id: 39,
    projectId: 5,
    fileName: "Typy (2)",
    fileType: "png",
    imagePath: "/assets/projects/Typy/Typy (2).png",
    projectName: "Typy",
  },
  {
    id: 40,
    projectId: 5,
    fileName: "Typy (3)",
    fileType: "png",
    imagePath: "/assets/projects/Typy/Typy (3).png",
    projectName: "Typy",
  },
  {
    id: 41,
    projectId: 5,
    fileName: "Typy (4)",
    fileType: "png",
    imagePath: "/assets/projects/Typy/Typy (4).png",
    projectName: "Typy",
  },

  {
    id: 41,
    projectId: 7,
    fileName: "MenuExtraction (1)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (1).png",
    projectName: "React Flow Menu Extraction",
  },
  {
    id: 42,
    projectId: 7,
    fileName: "MenuExtraction (2)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (2).png",
    projectName: "React Flow Menu Extraction",
  },
  {
    id: 43,
    projectId: 7,
    fileName: "MenuExtraction (3)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (3).png",
    projectName: "React Flow Menu Extraction",
  },
  {
    id: 44,
    projectId: 7,
    fileName: "MenuExtraction (4)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (4).png",
    projectName: "React Flow Menu Extraction",
  },
  {
    id: 45,
    projectId: 7,
    fileName: "MenuExtraction (5)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (5).png",
    projectName: "React Flow Menu Extraction",
  },
  {
    id: 46,
    projectId: 7,
    fileName: "MenuExtraction (6)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (6).png",
    projectName: "React Flow Menu Extraction",
  },
  {
    id: 47,
    projectId: 7,
    fileName: "MenuExtraction (7)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (7).png",
    projectName: "React Flow Menu Extraction",
  },
  {
    id: 48,
    projectId: 7,
    fileName: "MenuExtraction (8)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (8).png",
    projectName: "React Flow Menu Extraction",
  },
  {
    id: 49,
    projectId: 7,
    fileName: "MenuExtraction (9)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (9).png",
    projectName: "React Flow Menu Extraction",
  },
  {
    id: 50,
    projectId: 7,
    fileName: "MenuExtraction (10)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (10).png",
    projectName: "React Flow Menu Extraction",
  },
  {
    id: 51,
    projectId: 7,
    fileName: "MenuExtraction (11)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (11).png",
    projectName: "React Flow Menu Extraction",
  },
  {
    id: 52,
    projectId: 7,
    fileName: "MenuExtraction (12)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (12).png",
    projectName: "React Flow Menu Extraction",
  },
  {
    id: 53,
    projectId: 7,
    fileName: "MenuExtraction (13)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (13).png",
    projectName: "React Flow Menu Extraction",
  },
  {
    id: 54,
    projectId: 7,
    fileName: "MenuExtraction (14)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (14).png",
    projectName: "React Flow Menu Extraction",
  },
  {
    id: 55,
    projectId: 7,
    fileName: "MenuExtraction (15)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (15).png",
    projectName: "React Flow Menu Extraction",
  },

  {
    id: 56,
    projectId: 8,
    fileName: "Eshop (1)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (1).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 57,
    projectId: 8,
    fileName: "Eshop (2)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (2).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 58,
    projectId: 8,
    fileName: "Eshop (3)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (3).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 59,
    projectId: 8,
    fileName: "Eshop (4)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (4).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 60,
    projectId: 8,
    fileName: "Eshop (5)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (5).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 61,
    projectId: 8,
    fileName: "Eshop (6)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (6).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 62,
    projectId: 8,
    fileName: "Eshop (7)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (7).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 63,
    projectId: 8,
    fileName: "Eshop (8)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (8).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 64,
    projectId: 8,
    fileName: "Eshop (9)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (9).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 65,
    projectId: 8,
    fileName: "Eshop (10)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (10).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 66,
    projectId: 8,
    fileName: "Eshop (11)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (11).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 67,
    projectId: 8,
    fileName: "Eshop (12)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (12).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 68,
    projectId: 8,
    fileName: "Eshop (13)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (13).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 69,
    projectId: 8,
    fileName: "Eshop (14)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (14).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 70,
    projectId: 8,
    fileName: "Eshop (15)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (15).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 71,
    projectId: 8,
    fileName: "Eshop (16)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (16).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 72,
    projectId: 8,
    fileName: "Eshop (17)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (17).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 73,
    projectId: 8,
    fileName: "Eshop (18)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (18).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 74,
    projectId: 8,
    fileName: "Eshop (19)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (19).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 75,
    projectId: 8,
    fileName: "Eshop (20)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (20).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 76,
    projectId: 8,
    fileName: "Eshop (21)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (21).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 77,
    projectId: 8,
    fileName: "Eshop (22)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (22).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 78,
    projectId: 8,
    fileName: "Eshop (23)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (23).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 79,
    projectId: 8,
    fileName: "Eshop (24)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (24).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 80,
    projectId: 8,
    fileName: "Eshop (25)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (25).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 81,
    projectId: 8,
    fileName: "Eshop (26)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (26).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 82,
    projectId: 8,
    fileName: "Eshop (27)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (27).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 83,
    projectId: 8,
    fileName: "Eshop (28)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (28).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 84,
    projectId: 8,
    fileName: "Eshop (29)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (29).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 85,
    projectId: 8,
    fileName: "Eshop (30)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (30).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 86,
    projectId: 8,
    fileName: "Eshop (31)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (31).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 87,
    projectId: 8,
    fileName: "Eshop (32)",
    fileType: "png",
    imagePath: "/assets/projects/Eshop/Eshop (32).png",
    projectName: "Eshop: Ecommerce app",
  },
  {
    id: 88,
    projectId: 10,
    fileName: "Quote (1)",
    fileType: "png",
    imagePath: "/assets/projects/Quote/Quote (1).png",
    projectName: "Quote",
  },
  {
    id: 89,
    projectId: 10,
    fileName: "Quote (2)",
    fileType: "png",
    imagePath: "/assets/projects/Quote/Quote (2).png",
    projectName: "Quote",
  },
  {
    id: 90,
    projectId: 10,
    fileName: "Quote (3)",
    fileType: "png",
    imagePath: "/assets/projects/Quote/Quote (3).png",
    projectName: "Quote",
  },
  {
    id: 91,
    projectId: 10,
    fileName: "Quote (4)",
    fileType: "png",
    imagePath: "/assets/projects/Quote/Quote (4).png",
    projectName: "Quote",
  },
  {
    id: 92,
    projectId: 10,
    fileName: "Quote (5)",
    fileType: "png",
    imagePath: "/assets/projects/Quote/Quote (5).png",
    projectName: "Quote",
  },
  {
    id: 93,
    projectId: 10,
    fileName: "Quote (6)",
    fileType: "png",
    imagePath: "/assets/projects/Quote/Quote (6).png",
    projectName: "Quote",
  },
  {
    id: 94,
    projectId: 10,
    fileName: "Quote (7)",
    fileType: "png",
    imagePath: "/assets/projects/Quote/Quote (7).png",
    projectName: "Quote",
  },
];
