export const pictures = [
  {
    id: 1,
    projectId: 4,
    fileName: "Kairos (1)",
    fileType: "png",
    imagePath: "/assets/projects/Kairos/Kairos (1).png",
  },
  {
    id: 2,
    projectId: 4,
    fileName: "Kairos (2)",
    fileType: "png",
    imagePath: "/assets/projects/Kairos/Kairos (2).png",
  },
  {
    id: 3,
    projectId: 4,
    fileName: "Kairos (3)",
    fileType: "png",
    imagePath: "/assets/projects/Kairos/Kairos (3).png",
  },
  {
    id: 4,
    projectId: 4,
    fileName: "Kairos (4)",
    fileType: "png",
    imagePath: "/assets/projects/Kairos/Kairos (4).png",
  },
  {
    id: 5,
    projectId: 4,
    fileName: "Kairos (5)",
    fileType: "png",
    imagePath: "/assets/projects/Kairos/Kairos (5).png",
  },
  {
    id: 6,
    projectId: 4,
    fileName: "Kairos (6)",
    fileType: "png",
    imagePath: "/assets/projects/Kairos/Kairos (6).png",
  },
  {
    id: 7,
    projectId: 4,
    fileName: "Kairos (7)",
    fileType: "png",
    imagePath: "/assets/projects/Kairos/Kairos (7).png",
  },
  {
    id: 8,
    projectId: 4,
    fileName: "Kairos (8)",
    fileType: "png",
    imagePath: "/assets/projects/Kairos/Kairos (8).png",
  },
  {
    id: 9,
    projectId: 4,
    fileName: "Kairos (9)",
    fileType: "png",
    imagePath: "/assets/projects/Kairos/Kairos (9).png",
  },
  {
    id: 10,
    projectId: 2,
    fileName: "Portfolio (1)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (1).png",
  },
  {
    id: 11,
    projectId: 2,
    fileName: "Portfolio (2)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (2).png",
  },
  {
    id: 12,
    projectId: 2,
    fileName: "Portfolio (3)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (3).png",
  },
  {
    id: 13,
    projectId: 2,
    fileName: "Portfolio (4)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (4).png",
  },
  {
    id: 14,
    projectId: 2,
    fileName: "Portfolio (5)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (5).png",
  },
  {
    id: 15,
    projectId: 2,
    fileName: "Portfolio (6)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (6).png",
  },
  {
    id: 16,
    projectId: 2,
    fileName: "Portfolio (7)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (7).png",
  },
  {
    id: 17,
    projectId: 2,
    fileName: "Portfolio (8)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (8).png",
  },
  {
    id: 18,
    projectId: 2,
    fileName: "Portfolio (9)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (9).png",
  },
  {
    id: 19,
    projectId: 2,
    fileName: "Portfolio (10)",
    fileType: "png",
    imagePath: "/assets/projects/Portfolio/Portfolio (10).png",
  },
  {
    id: 20,
    projectId: 1,
    fileName: "TaskMate (1)",
    fileType: "png",
    imagePath: "/assets/projects/TaskMate/TaskMate (1).png",
  },
  {
    id: 21,
    projectId: 1,
    fileName: "TaskMate (2)",
    fileType: "png",
    imagePath: "/assets/projects/TaskMate/TaskMate (2).png",
  },
  {
    id: 22,
    projectId: 1,
    fileName: "TaskMate (3)",
    fileType: "png",
    imagePath: "/assets/projects/TaskMate/TaskMate (3).png",
  },
  {
    id: 23,
    projectId: 1,
    fileName: "TaskMate (4)",
    fileType: "png",
    imagePath: "/assets/projects/TaskMate/TaskMate (4).png",
  },
  {
    id: 24,
    projectId: 1,
    fileName: "TaskMate (5)",
    fileType: "png",
    imagePath: "/assets/projects/TaskMate/TaskMate (5).png",
  },
  {
    id: 25,
    projectId: 1,
    fileName: "TaskMate (6)",
    fileType: "png",
    imagePath: "/assets/projects/TaskMate/TaskMate (6).png",
  },
  {
    id: 26,
    projectId: 1,
    fileName: "TaskMate (7)",
    fileType: "png",
    imagePath: "/assets/projects/TaskMate/TaskMate (7).png",
  },
  {
    id: 27,
    projectId: 1,
    fileName: "TaskMate (8)",
    fileType: "png",
    imagePath: "/assets/projects/TaskMate/TaskMate (8).png",
  },
  {
    id: 28,
    projectId: 3,
    fileName: "MoviePlus (1)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (1).png",
  },
  {
    id: 29,
    projectId: 3,
    fileName: "MoviePlus (2)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (2).png",
  },
  {
    id: 30,
    projectId: 3,
    fileName: "MoviePlus (3)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (3).png",
  },
  {
    id: 31,
    projectId: 3,
    fileName: "MoviePlus (4)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (4).png",
  },
  {
    id: 32,
    projectId: 3,
    fileName: "MoviePlus (5)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (5).png",
  },
  {
    id: 33,
    projectId: 3,
    fileName: "MoviePlus (6)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (6).png",
  },
  {
    id: 34,
    projectId: 3,
    fileName: "MoviePlus (7)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (7).png",
  },
  {
    id: 35,
    projectId: 3,
    fileName: "MoviePlus (8)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (8).png",
  },
  {
    id: 36,
    projectId: 3,
    fileName: "MoviePlus (9)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (9).png",
  },
  {
    id: 37,
    projectId: 3,
    fileName: "MoviePlus (10)",
    fileType: "png",
    imagePath: "/assets/projects/MoviePlus/MoviePlus (10).png",
  },
  {
    id: 38,
    projectId: 5,
    fileName: "Typy (1)",
    fileType: "png",
    imagePath: "/assets/projects/Typy/Typy (1).png",
  },
  {
    id: 39,
    projectId: 5,
    fileName: "Typy (2)",
    fileType: "png",
    imagePath: "/assets/projects/Typy/Typy (2).png",
  },
  {
    id: 40,
    projectId: 5,
    fileName: "Typy (3)",
    fileType: "png",
    imagePath: "/assets/projects/Typy/Typy (3).png",
  },
  {
    id: 41,
    projectId: 5,
    fileName: "Typy (4)",
    fileType: "png",
    imagePath: "/assets/projects/Typy/Typy (4).png",
  },

  {
    id: 41,
    projectId: 7,
    fileName: "MenuExtraction (1)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (1).png",
  },
  {
    id: 42,
    projectId: 7,
    fileName: "MenuExtraction (2)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (2).png",
  },
  {
    id: 43,
    projectId: 7,
    fileName: "MenuExtraction (3)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (3).png",
  },
  {
    id: 44,
    projectId: 7,
    fileName: "MenuExtraction (4)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (4).png",
  },
  {
    id: 45,
    projectId: 7,
    fileName: "MenuExtraction (5)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (5).png",
  },
  {
    id: 46,
    projectId: 7,
    fileName: "MenuExtraction (6)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (6).png",
  },
  {
    id: 47,
    projectId: 7,
    fileName: "MenuExtraction (7)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (7).png",
  },
  {
    id: 48,
    projectId: 7,
    fileName: "MenuExtraction (8)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (8).png",
  },
  {
    id: 49,
    projectId: 7,
    fileName: "MenuExtraction (9)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (9).png",
  },
  {
    id: 50,
    projectId: 7,
    fileName: "MenuExtraction (10)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (10).png",
  },
  {
    id: 51,
    projectId: 7,
    fileName: "MenuExtraction (11)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (11).png",
  },
  {
    id: 52,
    projectId: 7,
    fileName: "MenuExtraction (12)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (12).png",
  },
  {
    id: 53,
    projectId: 7,
    fileName: "MenuExtraction (13)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (13).png",
  },
  {
    id: 54,
    projectId: 7,
    fileName: "MenuExtraction (14)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (14).png",
  },
  {
    id: 55,
    projectId: 7,
    fileName: "MenuExtraction (15)",
    fileType: "png",
    imagePath: "/assets/projects/MenuExtraction/MenuExtraction (15).png",
  },
];
