import { Project } from "./types";

export const projects: Project[] = [
  {
    id: 1,
    projectName: "Task Mate",
    status: true,
    platform: "Web",
    createdAt: "2023-05-01T10:15:30Z",
    updatedAt: "2023-06-01T11:00:00Z",
    description:
      "Task mate is a simple SPA where you can manage your simple day to day tasks.",
    features: [
      "Add a task to be completed",
      "Remove task if it is not required",
      "Update task title and time",
      "Mark tasks as completed or not",
    ],
    stack: ["ReactJS", "CSS", "React Toastfify", "Timeago React"],
    deploymentLink: "https://taskmate-beryl.vercel.app/",
    repository: "https://github.com/Sukkoth/ReactTuts",
  },
  {
    id: 2,
    projectName: "Portfolio",
    status: true,
    platform: "Web",
    createdAt: "2023-04-15T08:20:45Z",
    updatedAt: "2023-05-20T09:30:25Z",
    description:
      "This is my old portfolio item I made using nodejs. I have used this portfolio for over a year. It is done in a dark mode and it has a cool interface with responsive layout.",
    features: [
      "Showcase my skills",
      "Show the tools I use to do my projects",
      "Comes with a form to send email directly to my inbox",
      "Email form submission",
    ],
    stack: ["NodeJs", "Express", "Node-MailJet"],
    repository: "https://github.com/Sukkoth/Portfolio/tree/Fullstack",
    deploymentLink: "https://portfolio-h9af.onrender.com",
    futurePlan: [
      "I have planned to replace this one with a better version of portfolio",
      "Make it have a unique look and feel",
      "Be creative on the new one",
    ],
  },
  {
    id: 3,
    projectName: "Movie Plus",
    status: true,
    platform: "Web",
    createdAt: "2023-03-10T14:25:10Z",
    updatedAt: "2023-04-15T16:45:50Z",
    description:
      "This is a project I did to practice fetching remote data from server. It is a simple app that lets you browser through movies with their genres and categories as a filtering options. ",
    features: [
      "Get top box office movies of all time",
      "Filtering options for genres",
      "Browsing using popular, top box office top rated and coming soon options",
      "Adding to and removing from favourite section",
      "Search functionality",
      "Responsive Layout",
    ],
    deploymentLink: "https://movie-plus-ten.vercel.app",
    repository: "https://github.com/Sukkoth/MoviePlus",
    stack: ["ReactJs", "React Icons", "React Router Dom", "Rapid API"],
    futurePlan: [
      "Redesign the layout",
      "Convert to TypeScript",
      "Use TanStack query",
    ],
  },
  {
    id: 4,
    projectName: "Kairos",
    status: true,
    platform: "Web",
    createdAt: "2023-02-20T09:10:55Z",
    updatedAt: "2023-03-22T10:50:30Z",
    description:
      "Kaioros is also a simple todo app. But what makes this one different is that, I did this little project to mess around with Ionic. Ionic is an open source UI toolkit for building performant, high-quality mobile apps using web technologies — HTML, CSS, and JavaScript — with integrations for popular frameworks like Angular, React, and Vue. It is used with Capacitor. Capacitor is a cross-platform native runtime that makes it easy to build performant mobile applications that run natively on iOS, Android, and more using modern web tooling. Representing the next evolution of Hybrid apps, Capacitor creates Web Native apps, providing a modern native container approach for teams who want to build web-first without sacrificing full access to native SDKs when they need it. (these texts are from their docs). I have tried installing the app on android but left the whole thing since it is better to use either Flutter or React Native for mobile apps.",
    features: [
      "Add Tasks and Manage Tasks",
      "Cool dashboard for tasks",
      "Simple Auth",
      "A nice UI look and feel",
    ],
    stack: [
      "Capacitor",
      "ReactJS",
      "Redux Toolkit",
      "React hook form",
      "Yup",
      "React Icons",
      "React Router Dom",
      "TailwindCSS",
    ],
    deploymentLink: "https://kairos-phi.vercel.app",
    repository: "https://github.com/Sukkoth/Kairos",
    futurePlan: [
      "Learn better language and environment for mobile app dev, which I am currently doing by learning flutter",
      "I have no intention of using both capacitor and Ionic for mobile development, NO WAY!",
    ],
  },
  {
    id: 5,
    projectName: "Typy",
    status: true,
    platform: "Web",
    createdAt: "2023-01-30T07:35:20Z",
    updatedAt: "2023-02-25T08:55:40Z",
    description:
      "Typy is a simle web interface for typing speed test. I did this project just to mess around with events in javascript and take a loot at the difference it has between browsers and especially between desktops and mobile devices. The thing is that there is a huge difference especially the way mobile phones handle keyboard inputs. Anyways this project let's you have simple test to check out your typing speed even though it is not that much an advanced app.",
    deploymentLink: "https://typy-sukkoth.vercel.app",
    repository: "https://github.com/Sukkoth/typing",
    features: [
      "Select time ranges between from given options",
      "Write as the cursor moves along the letters you are typing",
      "Track user's accuracy",
      "Start over the test if you want",
      "Get a report for your test",
    ],
    futurePlan: [
      "Auth to track user progress and results",
      "Mobile devices better compatibility (keyboard events are so messed up on mobile devices 🙃)",
    ],
    stack: ["ReactJs", "TypeScript", "TailwindCSS", "React Icons"],
  },
  {
    id: 6,
    projectName: "TaskStar",
    status: false,
    platform: "Web",
    createdAt: "2023-01-30T07:35:20Z",
    updatedAt: "2023-02-25T08:55:40Z",
  },
  {
    id: 7,
    projectName: "Menu Extraction",
    status: true,
    platform: "Web",
    createdAt: "2023-01-30T07:35:20Z",
    updatedAt: "2023-02-25T08:55:40Z",
    description:
      "This is a project given as a exam from EPhone company. It was basically to showcase our React and problem solving skills. It is a simple web app to extract menus from given text input and show them using React flow package which is used to show and work with nodes for react apps. I engaged in the challenge as I was confident that I can do it. I completed the project in 24 hours and submitted and got a good feedback and earned a top spot for the 5 programmers required for interview.",
    features: [
      "Take list of menus as 1. MenuItem1 2. MenuItem2 from the user",
      "Extract the valid menus",
      "Show the extracted menus in the React Flow panel",
      "Connect nodes and showcase the order",
      "Add nodes if your require to have more",
      "Update any node you require to be updated",
      "Duplicate nodes and also delete unnesecary nodes",
      "Clear out all the nodes",
    ],
    deploymentLink: "https://reactflowmenuextraction.onrender.com",
    repository: "https://github.com/Sukkoth/ReactFlowMenuExtraction/tree/main",
    stack: ["ReactJS", "TypeScript", "React Flow", "TailwindCSS"],
    futurePlan: [
      "No plan to work on this project since it is alread done and nicely finished.",
      "But I have a plan to use React flow in more of my projects in the future.",
    ],
  },

  {
    id: 8,
    projectName: "Eshop",
    status: true,
    platform: "Web",
    createdAt: "2023-01-30T07:35:20Z",
    updatedAt: "2023-02-25T08:55:40Z",
    description:
      "This is a project I did to show my react skills back then. I made a fullstack ecommerce app from a scratch and this one is the client side version. I have invested a lot at that time since I just learned react and wanted to test skills on it while also building its backend myself.",
    features: [
      "A Login and Registration feature",
      "Carousel based products showcase",
      "Show popular and featured projects",
      "Browse through products",
      "Filter using categories",
      "Look at product details and its variants (Color, Size, etc)",
      "Adding to and managing favourites",
      "Adding to and managing Cart",
      "Check out products in cart",
      "Payment Method integration using Stripe",
      "View your orders",
      "Responsive layout",
    ],
    deploymentLink: "https://eshop-2fzq.onrender.com",
    repository: "https://github.com/Sukkoth/React-e-com/tree/wishList",
    stack: [
      "ReactJs",
      "Redux Toolkit",
      "Axios",
      "React Router Dom",
      "React hook form",
      "React Spinners",
      "Yup",
      "SwipperJS",
      "Vanilla CSS",
    ],
    futurePlan: [
      "The look now feels too old. Implement a new modern design to it. Using tailwind if possible",
      "Add new features",
    ],
  },

  {
    id: 9,
    projectName: "Eshop Backend",
    status: true,
    platform: "Backend",
    createdAt: "2023-01-30T07:35:20Z",
    updatedAt: "2023-02-25T08:55:40Z",
    description:
      "This one is the backend service for the Eshop app. I did this one and the other client app to showcase my MERN stack skills (Even though it is kinda old now). I have invested a lot into making this project work and be the one project to be showed on my portfolio. I have used the REST API model and JWT for authentication. Used MongoDB for the database and other tech stacks.",
    features: [
      "Authentication (Login and Registration)",
      "Projects feature",
      "Categories Feature",
      "Order Feature",
      "Cart Feature",
      "Database Integration with MongodDb",
      "Schema validation for data inputs",
    ],
    deploymentLink: "https://eshop-goky.onrender.com",
    repository: "https://github.com/Sukkoth/ecommerce/tree/payment",
    stack: [
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "Mongoose",
      "Stripe",
      "Morgan for logging",
      "JOI: For schema validation",
      "Bcrypt",
      "JWT",
    ],
    futurePlan: ["May be migrate to NestJS"],
  },
  {
    id: 10,
    projectName: "Quote Generator",
    status: true,
    platform: "Web",
    createdAt: "2023-01-30T07:35:20Z",
    updatedAt: "2023-02-25T08:55:40Z",
    description:
      "This was almost the first time I started to learn how to fetch data from API in reactjs. I did this as my first project to practice what I have learned from tutorials. This simple and mini little app can fetch random quotes from public api and show it. You can then share the quote on both telegram and X (a.k.a Twitter)",
    features: [
      "Fetch quotes from public API",
      "Share on Telegram with friends or channels or groups",
      "Tweet the quote on your X account",
    ],
    deploymentLink: "https://quote-generator-em8b.onrender.com",
    repository: "https://github.com/Sukkoth/ReactTuts/tree/QuoteGenerator",
    futurePlan: ["I got no future plans for this specific project 🤣"],
    stack: ["ReactJS", "Axios", "Vanilla CSS"],
  },
];
